option(WXL_STORY_SELECT_TRIAL "Opt-in selected actor capability probe" OFF)
if(WXL_STORY_SELECT_TRIAL)
    if(CLIENT_PATH)
        message(FATAL_ERROR "Story selector trial must build offline; CLIENT_PATH must be empty")
    endif()
    target_compile_definitions(WarcraftXL PRIVATE WXL_STORY_SELECT_TRIAL=1)
endif()
add_executable(wxl-story-select-test EXCLUDE_FROM_ALL tests/story_select_test.cpp)
target_include_directories(wxl-story-select-test PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/src")
target_compile_options(wxl-story-select-test PRIVATE /UNDEBUG)

option(WXL_CHARACTER_CAPACITY_TRIAL "Native 50-character roster and read-only identity" OFF)
if(WXL_CHARACTER_CAPACITY_TRIAL)
    if(CLIENT_PATH)
        message(FATAL_ERROR "Character capacity must build offline; CLIENT_PATH must be empty")
    endif()
    target_compile_definitions(WarcraftXL PRIVATE WXL_CHARACTER_CAPACITY_TRIAL=1)
endif()
